#!/bin/bash
# ------------------------------------------------------------------
#title                  :run_Charger_on_VEP.sh
#description            :This script will run CharGer on an input VEP annotated VCF.
#author                 :Fernanda Martins Rodrigues (fernanda)
#usage                  :bash run_CharGer_on_VEP.sh -I [input_sample.vcf] -o [output basename] -O [output_directory] -L [logs_directory]
#notes                  :Install CharGer to use this script
#bash_version           :4.2.46(2)-release (x86_64-redhat-linux-gnu)
#CharGer_version        :0.5.4
# ------------------------------------------------------------------

USAGE="Usage: bash run_CharGer_on_VEP.sh -I [input_sample.vcf] -o [output basename] -O [output_directory] -L [logs_directory]"

# --- Options processing -------------------------------------------

while getopts "I:a:o:O:L:" opt; do
	case $opt in
		I)
			INPUT_VCF=$OPTARG # input VEP annotated VCF file
			;;
		o)
			OUT_FILENAME=$OPTARG # basename for output file
			;;
		O)
			OUT_DIR=$OPTARG # output directory
			;;
		L)
			LOGS=$OPTARG # logs directory
			;;
		\?)
			echo "Invalid option -$OPTARG"
			echo $USAGE
			exit 1
			;;
		:)
			echo "Option -$OPTARG requires an argument."
			echo $USAGE
			exit 1
			;;
	esac
done

if [ "$#" -ne 8 ] ; then
	echo "Invalid number of arguments."
	echo $USAGE
	exit 1;
fi

# --- Body ----------------------------------------------------------

if [ ! -d ${OUT_DIR} ]; then
	mkdir "${OUT_DIR}"
fi

if [[ ${OUT_DIR: -1} != "/" ]]; then
	OUT_DIR=${OUT_DIR}/
fi

if [ ! -d ${LOGS} ]; then
	mkdir "${LOGS}"
fi

if [[ ${LOGS: -1} != "/" ]]; then
	LOGS=${LOGS}/
fi

### CharGer cross-reference data files

# clinvar file (08-15-2019) can be downloaded from: https://github.com/fernanda-rodrigues/ClinVar/raw/20190815_release/output/b38/single/clinvar_alleles.single.b38.tsv.gz

clinvar_b38="/gscmnt/gc3020/dinglab/fernanda/Projects/CharGer_testing/ClinVar/clinvar_alleles.single.b38.tsv.gz"

# Using same files generated by Huang et al (2018) TCGA germline study, however lifted over to grch38 coordinates: https://doi.org/10.1016/j.cell.2018.03.039

cancer_predis_genes="/gscmnt/gc3021/dinglab/fernanda/PDX_germline/6.CharGer/CharGer-0.5.4/PanCanAtlasData/20160301_Rahman_KJ_KH_gene_table_CharGer.txt"

pp2list="/gscmnt/gc3021/dinglab/fernanda/PDX_germline/6.CharGer/CharGer-0.5.4/PanCanAtlasData/152_cpgs.txt"
variants_b38="/gscmnt/gc3021/dinglab/fernanda/PDX_germline/6.CharGer/CharGer-0.5.4/PanCanAtlasData/emptyRemoved_20160428_pathogenic_variants_HGVSg_VEP_grch38lifOver.vcf"
hotspot_b38="/gscmnt/gc3021/dinglab/fernanda/PDX_germline/6.CharGer/CharGer-0.5.4/PanCanAtlasData/MC3.noHypers.mericUnspecified.d10.r20.v114.grch38liftOver.clusters"

rareThreshold="0.0005"

# Run CharGer

conda activate CharGer

bsub -q research-hpc -n 1 -R "select[mem>30000] rusage[mem=30000]" -M 30000000 -a 'docker(registry.gsc.wustl.edu/genome/genome_perl_environment)' -oo ${LOGS}${OUT_FILENAME}.charger.log charger --include-vcf-details -f ${INPUT_VCF} -o ${OUT_DIR}${OUT_FILENAME}.charged.tsv -O -D --inheritanceGeneList ${cancer_predis_genes} --PP2GeneList ${pp2list} -z ${variants_b38} -H ${hotspot_b38} -l --mac-clinvar-tsv ${clinvar_b38} --rare-threshold ${rareThreshold}


# --- End -----------------------------------------------------------
